from matplotlib import pyplot as plt
!pip install geopandas
import pandas as pd
import geopandas as gpd
import numpy as np
import datetime

import plotly.express as px
import plotly.graph_objects as go

gdf = gpd.GeoDataFrame.from_file('https://docs.google.com/uc?id=1JXdn72Ur1fMMXCfksNqt5b-7JCD0-WAV&export=download')

#this is me isolating crude-looking Ireland bc I can
mask = gdf['ADMIN'] == 'Ireland'
gdf[mask].plot()

df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSHo1FzmCpYdNRoMgBZSPTzxhHE-yI0bRohAvi0QetFhIF6MlZfpxGKXwyg5Zxm37jniEQWXC5Pm9O1/pub?output=csv')
df

merged = gdf.merge(df, left_on='ADMIN', right_on='Entity')

merged = merged.loc[merged.Year == 2010,:]

fig = go.Figure(data=go.Choropleth(
    locations = merged['GU_A3'],
    z = merged['Plastic waste generated (% global total)'],
    text = merged['Entity'],
    colorscale = 'Blues',
    autocolorscale=False,
    reversescale=True,
    marker_line_color='darkgray',
    marker_line_width=0.5,
    colorbar_ticksuffix = '%',
    colorbar_title = '% of Global Total',
))

fig.update_layout(
    title_text='Plastic Waste Generated By Country in 2010',
    geo=dict(
        showframe=False,
        showcoastlines=False,
        projection_type='equirectangular'
    ),
    annotations = [dict(
        x=0.55,
        y=0.1,
        xref='paper',
        yref='paper',
        text='Source: <a href="https://github.com/owid/owid-datasets/blob/master/datasets/Plastic%20waste%20percentages%20-%20Jambeck%20et%20al.%20(2015)/README.md#plastic-waste-percentages---jambeck-et-al-2015.html">\
            GitHub</a>',
        showarrow = False
    )]
)

fig.show()

merged = gdf.merge(df, left_on='ADMIN', right_on='Entity')

merged = merged.loc[merged.Year == 2025,:]

fig = go.Figure(data=go.Choropleth(
    locations = merged['GU_A3'],
    z = merged['Plastic waste generated (% global total)'],
    text = merged['Entity'],
    colorscale = 'Blues',
    autocolorscale=False,
    reversescale=True,
    marker_line_color='darkgray',
    marker_line_width=0.5,
    colorbar_ticksuffix = '%',
    colorbar_title = '% of Global Total',
))

fig.update_layout(
    title_text='Projected Plastic Waste Generated By Country in 2025',
    geo=dict(
        showframe=False,
        showcoastlines=False,
        projection_type='equirectangular'
    ),
    annotations = [dict(
        x=0.55,
        y=0.1,
        xref='paper',
        yref='paper',
        text='Source: <a href="https://github.com/owid/owid-datasets/blob/master/datasets/Plastic%20waste%20percentages%20-%20Jambeck%20et%20al.%20(2015)/README.md#plastic-waste-percentages---jambeck-et-al-2015.html">\
            GitHub</a>',
        showarrow = False
    )]
)

fig.show()
